[tool.poetry]
name = "silverrail"
version = "0.1.0"
description = ""
authors = ["Ash Omaraie <49348213+aomarai@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
